spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/testdb
#    username: testuser
#    password: testpass
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    url: jdbc:h2:mem:test-db
    username: sa
    password:
    driver-class-name: org.h2.Driver

  data:
    mongodb:
      uri: mongodb://localhost:27017/testdb

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
